<!doctype html>
<html lang="en">
<head>
    <title>First page</title>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
<h1>Основы. Вот это заголовок!</h1>
<p>Это обычный текст, а вот так <em>можно сделать его курсивом</em> а еще вставить <br> разрыв строки</p>
<a href="https://github.com/SofiazaR/Alabania">Добавляем ссылку, хочу что бы вела на гит с этим проектом:)</a>
<p></p>
<a href="https://github.com/SofiazaR/Alabania" target="_blank">Та же ссылка, только откроется в соседней странице<br></a>

<button disabled>Кнопка на которую нельзя нажать</button>
</body>
</html>
